version: "3.9"
services:
  client:
    build:
      context: client
      args:
        SERVER_URL: http://localhost:3001
    ports:
      - 3000:80
  server:
    build: server
    ports:
      - 3001:3001
